const projects = [
  {
    title: "Stacking Your Squad",
    description: "Command-line application that helps a user to build a team",
    technology: [
      "Javascript",
      "HTML/CSS",
      "Command-line Application",
      "Node.js",
      "Inquirer",
      "Jest",
    ],
    image: require("../src/project-screenshots/project-gifs/stacking-your-squad.gif"),
    github: "https://github.com/AmberZimmerman/stacking_your_squad",
    deployed: "",
    videolink:
      "https://drive.google.com/file/d/1dkVYjO1oYt4Z6aMn3xa9273rPobtBAv-/view?usp=sharing",
  },
  {
    title: "Secure Password Generator",
    description:
      "User can generate their own secure password by choosing specific criteria based on given options. ",
    technology: ["Javascript", "HTML/CSS"],
    image: require("../src/project-screenshots/generated-password-ss1.png"),
    demogif: "",
    github: "https://github.com/AmberZimmerman/secure-password-generator",
    deployed: "https://amberzimmerman.github.io/secure-password-generator/",
    videolink: "",
  },
  {
    title: "Dolly Work Day Planner",
    description:
      "A Dolly Parton themed day planner that allows a user to schedule in hourly tasks. Hourly tasks will change background color in real time. Tasks can be saved to local storage.",
    technology: ["Javascript", "HTML/CSS", "Local Storage", "Moment.js"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/dolly-workday-planner",
    deployed: "https://github.com/AmberZimmerman/dolly-workday-planner",
    videolink: "",
  },
  {
    title: "Ambers Magical Weather App",
    description: "",
    technology: ["Javascript", "HTML/CSS", "API", "Local Storage", "Bootstrap"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/ambers-magical-weather-app",
    deployed: "https://amberzimmerman.github.io/ambers-magical-weather-app/",
    videolink: "",
  },
  {
    title: "Never Miss A Note",
    description:
      "This app allows a user to write, save, and delete notes. Begin by selecting the new note and then typing a title then a description below. Once finished the user can click the floppy disk to save the note.",
    technology: ["Javascript", "HTML/CSS", "Bootstrap", "Node.js", "Express"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/never_miss_a_note",
    deployed: "https://never-miss-a-note.herokuapp.com/",
    videolink: "",
  },
  {
    title: "Categorizing Your Clique",
    description:
      "This content management system allows the user to organize aspects of their business by viewing details about the departments, roles, and employees in the database.",
    technology: ["Javascript", "CMS", "Node.js", "Inquirer", "MySQL"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/categorizing_your_clique",
    deployed: "",
    videolink:
      "https://drive.google.com/file/d/14HoVuqsNcQepHpJSzImUIlFpxoWSUZb6/view?usp=sharing",
  },
  {
    title: "Ecommerce Everything Pencils",
    description:
      "The is the backend component to a ecommerce site for an online retail store. It meets MVP criteria. An Express.js API was built to use Sequelize to interact with a MySQL database.",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/ecommerce-everything-pencils",
    deployed: "",
    videolink:
      "https://drive.google.com/drive/folders/1aPcGE6_DMf_JfofeDzrjpkjgzBzFul_Q?usp=sharing",
  },
  {
    title: "Just Another Text Editor",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
  {
    title: "Personal Readme Generator",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/ambers_easy_readme_maker",
    deployed: "",
    videolink: "",
  },
  {
    title: "Fussy Flamingo",
    description:
      "A silly little quiz about flamingos using vanilla javascript and html/css. Keeps track of scores and lets users save them in local storage.",
    technology: ["Javascript", "HTML/CSS", "Local Storage"],
    image: "",
    demogif: "",
    github: "https://github.com/AmberZimmerman/fussy-flamingos-timed-quiz",
    deployed: "https://amberzimmerman.github.io/fussy-flamingos-timed-quiz/",
    videolink: "",
  },
  {
    title: "Accretion",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
  {
    title: "MOONR8KER",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
  {
    title: "Final prjt",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
  {
    title: "Denver Harlequins Rugby?",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
  {
    title: "On Second Thought",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
  {
    title: "Regex Tutorial",
    description: "",
    technology: ["Javascript", "Express", "API", "Sequelize", "MySQL"],
    image: "",
    demogif: "",
    github: "",
    deployed: "",
    videolink: "",
  },
];

export default projects;
